Repository sparta-USD/Na-dle, pull requests merged in 2022-11, with the labels that each got.

#9 Feat: Music 모델 생성 #6
  musics/admin.py
  musics/models.py
  musics/serializers.py
Labels: enhancement

#15 Feat : spotify API를 활용한 음원 데이터셋 생성
  music_data.csv
  musics/dataset.py
  test.csv
Labels: enhancement

#24 Feat: 추천시스템 협업 필터링 및 추천음악리스트 출력 구현
  grades_data.csv
  music_data.csv
  music_data.json
  music_data_for_db.json
  music_loader.py
  musics/dataset.py
  musics/dummy.py
  musics/recommand.py
  user_distance_data.csv
Labels: enhancement

#25 Feat: 협업필터링 이용, 비슷한 취향의 유저 반환 함수 #18
  musics/recommend.py
Labels: enhancement

#28 Feat: 테스트 유저들 생성, 협업필터링 이용 View에서 API로 사용 가능 #26
  musics/migrations/0001_initial.py
  musics/models.py
  musics/recommend.py
  musics/serializers.py
  musics/urls.py
  musics/views.py
  nadle/settings.py
  nadle/urls.py
  requirements.txt
  users/admin.py
  users/management/__init__.py
  users/management/commands/__init__.py
  users/management/commands/create-users.py
  users/migrations/0001_initial.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#30 Feat: 추천시스템-Django 연결 완료, 파일정리
  data/grades_data.csv
  data/music_data.csv
  data/music_data.json
  data/music_data_for_db.json
  data/user_distance_data.csv
  grades_data.csv
  music_loader.py
  musics/dataset.py
  musics/dummy.py
  musics/recommend.py
  musics/views.py
  test.csv
  user_distance_data.csv
  users/serializers.py
Labels: enhancement

#31 Feat: 협업필터링을 이용한 추천시스템 기능 구현 완료
  data/grades_data.csv
  data/music_data.csv
  data/music_data.json
  data/music_data_for_db.json
  data/user_distance_data.csv
  music_loader.py
  musics/dataset.py
  musics/dummy.py
  musics/recommend.py
  musics/views.py
  nadle/settings.py
  requirements.txt
  users/management/__init__.py
  users/management/commands/__init__.py
  users/management/commands/create-users.py
  users/models.py
  users/serializers.py
Labels: enhancement

#33 Feat: 프론트엔드 작업을 위한 CORS 허용 추가 #32
  nadle/settings.py
  requirements.txt
Labels: enhancement

#38 Feat: 선호도조사 - 랜덤 음악 추출 API
  musics/urls.py
  musics/views.py
Labels: enhancement

#40 Fix: 유저프로필 잘못된 API 경로 수정 #39
  musics/migrations/0002_alter_review_user.py
  users/migrations/0002_alter_user_follow.py
  users/urls.py
  users/views.py
Labels: bug

#34 Feat: 유저 프로필 페이지 구현 #27
  musics/migrations/0001_initial.py
  musics/models.py
  users/migrations/0001_initial.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#43 Feat: 전체음원 조회 API 구현
  musics/urls.py
  musics/views.py
Labels: bug, enhancement

#44 Feat: 음원의 평균 리뷰 점수 추가 #35
  musics/models.py
  musics/serializers.py
Labels: enhancement

#45 Feat : 프로필상세페이지 API 부족한 데이터 추가
  data/grades_data.csv
  data/user_distance_data.csv
  musics/migrations/0001_initial.py
  musics/migrations/0002_alter_review_user.py
  musics/serializers.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_follow.py
  users/views.py
Labels: enhancement

#49 Refactor: Review API 리뉴얼
  musics/serializers.py
  musics/urls.py
  musics/views.py
Labels: bug, enhancement

#48 Feat: 회원가입시 아이디 중복검사 추가 #47
  users/views.py
Labels: enhancement

#51 Rename: 로그인페이지에 대한 url, view 이름만 변경 #50
  users/urls.py
  users/views.py
Labels: enhancement

#52 Feat : MusicSimpleSerializer fields 추가
  data/grades_data.csv
  data/user_distance_data.csv
  musics/serializers.py
Labels: enhancement

#54 Feat: 유저 프로필 페이지에 팔로우 데이터 보내기 #53
  users/serializers.py
  users/views.py
Labels: enhancement

#57 Feat: 첫 로그인일 경우만 선호도조사 페이지로 이동 #56
  data/grades_data.csv
  data/user_distance_data.csv
  musics/serializers.py
  musics/views.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement

#58 Fix: 추천시스템 동작시 에러 해결 완료 #55
  musics/serializers.py
  musics/views.py
Labels: bug
